# Documentation: http://docs.travis-ci.com/user/languages/julia/
dist: trusty
sudo: required
language: julia
os:
  - linux
julia:
  - 0.5
  - nightly
notifications:
  email: false       
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgtk-3-dev xvfb xauth
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia ./test/install_SS.jl
  - xvfb-run julia --check-bounds=yes --depwarn=no -e 'Pkg.clone(pwd()); Pkg.build("Intan"); Pkg.test("Intan"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Intan")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
